---
# tasks/cleanup.yml

- name: ocStore | Backup | Delete temporary directory
  file:
    path: "{{ tmp_dir.path }}"
    state: "absent"

- name: ocStore | Backup | Clean up remote backups
  shell: ls -1dt {{ ocstore_backup_to }}/* | tail -n +{{ ocstore_backup_keep | int + 1 }} | xargs rm -rf
  when: ocstore_backup_keep > 0

- name: ocStore | Backup | Clean up local backups
  local_action: shell ls -1dt {{ playbook_dir }}/{{ ocstore_backup_dir }}/* | tail -n +{{ ocstore_backup_keep | int + 1 }} | xargs rm -rf
  when: ocstore_backup_keep > 0
