---
# tasks/files.yml

- name: ocStore | Backup | Sync files
  shell: "rsync -amq {{ item.options | default([]) | join(' ') }} {{ item.path }} {{ tmp_dir.path }}/{{ ocstore_backup_files_dir }}"
  with_items: "{{ ocstore_backup_from }}"
  become: yes
